import EachDirectionComponent from "@/components/direction/EachDirectionComponent";
import { Metadata } from "next";
import React from "react";

export async function generateMetadata({ params }: any): Promise<Metadata> {
  return {
    title: `Direction ${params.directionId}`, // Dynamically set the title
    description: "Generated by create next app",
  };
}

const Page = ({ params }: any) => {
  return (
    <main>
      <EachDirectionComponent id={params.directionId} />
    </main>
  );
};

export default Page;
